/* config.h.  Generated by configure.  */
#ifndef CONFIG_H
#define CONFIG_H

#define VERSION "1.1c"
#define MAX_CPP_ARGS 100
#define PREFIX "@@@splitdefs "

#define CPP "gcc -E"
/* The location of the C preprocessor (typically /lib/cpp) */
#define CPP_ARG "-"
/* Extra argument to give the C preprocessor (e.g. -) to make it read
   from standard input */

#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDARG_H 1
#define HAVE_ASSERT_H 1
#define HAVE_STRING_H 1
#define HAVE_FCNTL_H 1

#endif /* CONFIG_H */
